site_name: BJM 用户手册

site_url: https://atticus.github.io/BJM_Document/
site_author: atticus

#Repository
#repo_name: atticus-lv/BJM_Document
#repo_url: https://github.com/atticus-lv/BJM_Document
#edit_uri: edit/master/docs/

# Plugins
plugins:
  - offline
  - search
  - blog
  - tags

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: custom/overrides

  logo: assets/bjm_b_white.png
  language: zh

  font:
    text: Inter
    code: Roboto Mono

  favicon: assets/favicon.ico

  palette:
    # Light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: 切换到深色模式
    # Dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: 切换到浅色模式

  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking

    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.footnote.tooltips

    - search.highlight
    - search.share
    - search.suggest

# Extensions
markdown_extensions:
  - stepslist
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
  - toc:
      title: On this page
      permalink: true
      toc_depth: 3

  - tables
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 主页: index.md
  - 常见问题:
      - QA/安装常见问题.md
      - QA/使用常见问题.md
      - QA/GOZ.GOB失败.md
      - 如何反馈bug: QA/bugReport.md
  - 功能查询:
      - 快捷键总览: functions/shortcuts.md
      - 3d视图: functions/view3d.md
      - 物体模式: functions/object_mode.md
      - 编辑模式: functions/edit_mode.md
      - 雕刻模式: functions/sculpt_mode.md
      - 其他菜单: functions/other_menu.md

  - 更新/发布:
    - blog/index.md